FROM openjdk:8

MAINTAINER Rovshan Guliyev

COPY /betPawa-wallet-client/build/libs/betPawa-wallet-client.jar /app/betPawa-wallet-client.jar

CMD ["java", "-jar", "/app/betPawa-wallet-client.jar"]

EXPOSE 9090