FROM openjdk:8

MAINTAINER Rovshan Guliyev

COPY /betPawa-wallet-server/build/libs/betPawa-wallet-server.jar /app/betPawa-wallet-server.jar

CMD ["java", "-jar", "/app/betPawa-wallet-server.jar"]

EXPOSE 9090